# Generated by Django 2.2.2 on 2021-09-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kikuchi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kikuchi',
        ),
    ]
